# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f32787cf20466f3889dd40eacaa9341876a7c3c1f8e495f886547cf2cf39c18b8cfb024b6c8aaaf45dc8850635b7e30f523343a0df411ca91ad304fd2b6425e2

test:
  secret_key_base: 80c5741bb07e095d9b85d2922ada869c43f326b273b83f05ac20c6d4591a264955ae65cab3596b78e1c00defe8b551a7ab0eff0ee24e82e2ae7b0d7ae0e3fcf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
